// Generated by CoffeeScript 1.4.0
(function() {
  var syncInfo;

  syncInfo = {
    "GCloud": {
      "key": '195693500289.apps.googleusercontent.com',
      "scope": 'https://www.googleapis.com/auth/devstorage.full_control',
      "app_name": "waiter-code-sample-bucket",
      "api_key": 'AIzaSyBVDs0bXkbSuflogzPL_JgMUPgRPXSDcCc',
      "project_id": "195693500289"
    }
  };

  Nimbus.Auth.setup(syncInfo);

  Nimbus.Auth.service = "GCloud";

  localStorage["app_name"] = "waiter-code-sample-bucket";

  window.folder = {
    "Post": "Post",
    "Comment": "Comment"
  };

  window.Post = Nimbus.Model.setup("Post", ["title", "link", "category", "create_time"]);

  window.Comment = Nimbus.Model.setup("Comment", ["postid", "comment", "name"]);

  window.UpVote = Nimbus.Model.setup("UpVote", ["postid", "voter"]);

  window.DownVote = Nimbus.Model.setup("DownVote", ["postid", "voter"]);

  window.Post.ordersort = function(a, b) {
    var x, y;
    x = Date(a.create_time);
    y = Date(b.create_time);
    if (x < y) {
      return -1;
    } else {
      return 1;
    }
  };

  Nimbus.Auth.set_app_ready(function() {
    if ((Nimbus.Auth.authorized != null) && Nimbus.Auth.authorized()) {
      localStorage["user_email"] = window.user_email;
      $("#loginfo").html("Logout");
      return window.Post.sync_all(function() {
        return window.Comment.sync_all();
      });
    } else if (!(localStorage["state"] === "Auth")) {
      localStorage["Post_count"] = window.Post.all().length;
      localStorage["Comment_count"] = window.Comment.all().length;
      return window.Post.sync_all(function() {
        return window.Comment.sync_all(function() {
          if (localStorage["Post_count"] < window.Post.all().length) {
            setTimeout("window.location.reload();", 3000);
          }
          if (localStorage["Comment_count"] < window.Comment.all().length) {
            return setTimeout("window.location.reload();", 3000);
          }
        });
      });
    }
  });

  window.Login_out = function() {
    if ((Nimbus.Auth.authorized != null) && Nimbus.Auth.authorized()) {
      Nimbus.Auth.logout();
      return window.location.reload();
    } else {
      return Nimbus.Auth.authorize('GCloud');
    }
  };

  window.addPost = function(title, link) {
    var post;
    post = {
      "title": title,
      "category": null,
      "link": link,
      "create_time": Date(),
      "owner": window.user_email
    };
    return window.Post.create(post);
  };

  window.EditPost = function(id, title, link) {
    var p;
    p = Post.find(id);
    p.title = title;
    p.link = link;
    return p.save();
  };

  window.addComment = function(postid) {
    var comment, newcomment;
    comment = $("#add_comment_" + postid).val();
    $("#add_comment_" + postid).val("");
    newcomment = {
      "postid": postid,
      "comment": comment,
      "owner": window.user_email,
      "name": window.user_name
    };
    return window.Comment.create(newcomment);
  };

  window.addUpVote = function(postid) {
    var newUpVote;
    newUpVote = {
      "postid": postid,
      "voter": window.user_email
    };
    return window.UpVote.create(newUpVote);
  };

  window.addDownVote = function(postid) {
    var newDownVote;
    newDownVote = {
      "postid": postid,
      "voter": window.user_email
    };
    return window.DownVote.create(newDownVote);
  };

}).call(this);
